import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/partial/header";
import { secondaryFont } from "@/theme/typography";
import { Roboto } from "next/font/google";
import { Footer } from "@/partial/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <main className="min-h-screen m-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
